export const FETCH_ITEM_SIMILAR_REQUEST = 'FETCH_ITEM_SIMILAR_REQUEST';
export const FETCH_ITEM_SIMILAR_SUCCESS = 'FETCH_ITEM_SIMILAR_SUCCESS';
export const FETCH_ITEM_SIMILAR_FAILURE = 'FETCH_ITEM_SIMILAR_FAILURE';