export const FETCH_ITEM_REQUEST = 'FETCH_ITEM_REQUEST';
export const FETCH_ITEM_SUCCESS = 'FETCH_ITEM_SUCCESS';
export const FETCH_ITEM_FAILURE = 'FETCH_ITEM_FAILURE';
export const SET_CURRENT_ITEM_DETAILS = 'SET_CURRENT_ITEM_DETAILS';
export const SET_ISLOADED_STATE = 'SET_ISLOADED_STATE';